Traceback (most recent call last):
  File "c:\users\uenergia\appdata\local\programs\python\python36\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\uenergia\appdata\local\programs\python\python36\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\uenergia\appdata\local\programs\python\python36\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\uenergia\appdata\local\programs\python\python36\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\uenergia\appdata\local\programs\python\python36\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File "c:\users\uenergia\appdata\local\programs\python\python36\lib\site-packages\nbclient\client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\uenergia\appdata\local\programs\python\python36\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\uenergia\appdata\local\programs\python\python36\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# importando librerias

# librerias para la transformaci√≥n de datos
import pandas as pd
import numpy as np
from datetime import datetime
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller
import statsmodels.api as sm
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA

# libreria para visualizaci√≥n de datos
import matplotlib.pyplot as plt
import seaborn as sns
from prophet import Prophet
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-1-dc094fca4d75>[0m in [0;36m<module>[1;34m[0m
[0;32m     15[0m [1;32mimport[0m [0mmatplotlib[0m[1;33m.[0m[0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0;32m     16[0m [1;32mimport[0m [0mseaborn[0m [1;32mas[0m [0msns[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 17[1;33m [1;32mfrom[0m [0mprophet[0m [1;32mimport[0m [0mProphet[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mModuleNotFoundError[0m: No module named 'prophet'
ModuleNotFoundError: No module named 'prophet'

